GitHub 978
CTemplar/webclient pull request #1032
Opened 2021-02-17 21:24 UTC by happyman125

Fixes #978 

### Changes description

  - typescript checking and null check

2021-02-17 21:28 UTC, happyman125 commented
@The-Hidden-Hand I didn't complete all null check because it will take more time. but completed code strong typing. So please review and let me know

2021-02-18 02:58 UTC, The-Hidden-Hand requested changes
Please review and ensure accurate types.

2021-02-18 02:58 UTC, The-Hidden-Hand commented on src/app/store/services/users.service.ts
> +  addWhiteList(email: any, name: any) {
Shouldn't be string types?

2021-02-18 02:58 UTC, The-Hidden-Hand commented on src/app/store/services/users.service.ts
> +  getAccounts(id: string) {
Shouldn't be a number type?

2021-02-18 02:58 UTC, The-Hidden-Hand commented on src/app/store/services/users.service.ts
> +  deleteBlackList(id: any) {
Shouldn't be a number type?

2021-02-18 02:58 UTC, The-Hidden-Hand commented on src/app/store/services/users.service.ts
> +  addBlackList(email: any, name: any) {
Shouldn't be string types?

2021-02-26 08:59 UTC, The-Hidden-Hand commented
@happyman125 
There are many types not properly defined. Modals should be `NgbModalRef`, and so on.

2021-02-26 09:37 UTC, The-Hidden-Hand commented
I may merge this PR after this week's release, and we do another iteration later keeping the issue open.

2021-02-26 15:22 UTC, merged