Dev 1790
CTemplar/webclient pull request #789
Opened 2020-09-14 16:25 UTC by superdev0714

Fixed Issue DEV-1790

1. fixed attachment forward dialog issue (no button repeat issue)
2. from, to field blank issue

2020-09-14 16:36 UTC, The-Hidden-Hand commented on src/app/mail/mail-detail/mail-detail.component.ts
> +      `From: ${mail.sender_display.name}&nbsp;&lt;${mail.sender_display.email}&gt;</br>` +
This will render <email> with empty display_name.

2020-09-14 16:36 UTC, The-Hidden-Hand commented on src/app/mail/mail-detail/mail-detail.component.ts
> +      `To: ${mail.receiver_display.map(receiver => `${receiver.name}&nbsp; &lt;${receiver.email}&gt;`).join(', ')}</br>`;
This will render <email> with empty display_name.

2020-09-14 16:39 UTC, The-Hidden-Hand requested changes
Two parts will render `<email>` with empty display_name.

2020-09-15 00:20 UTC, closed without merging

2020-09-15 00:21 UTC, superdev0714 commented
Need to check for reply part